### ISSUE TITLE
Call to undefined method App\\Model\\Admin\\AdminModel::updateWithLimit()

### ISSUE THREAD

**Issue by shaoyuanpeng2** [XueSiLf/demo-3.7.x#1]
demo 中，访问api/admin/auth/login?account=easyswoole&password=123456
报错：Call to undefined method App\\Model\\Admin\\AdminModel::updateWithLimit()
实际查看App\\Model\\Admin\\AdminModel类中，确实没有updateWithLimit 方法

**Comment by XueSiLf** [comment]
> demo 中，访问api/admin/auth/login?account=easyswoole&password=123456 报错：Call to undefined method App\Model\Admin\AdminModel::updateWithLimit() 实际查看App\Model\Admin\AdminModel类中，确实没有updateWithLimit 方法

已修复。请拉取最新代码。
